routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/jumlah-ruas-jalan', 'ApiForDashboardController@jumlah_ruas_jalan');
Route::get('/data-kondisi-jalan', 'ApiForDashboardController@data_kondisi_jalan');
Route::get('/total-konstruksi-jalan', 'ApiForDashboardController@total_konstruksi_jalan');
Route::get('/data-jalan-all', 'ApiForDashboardController@all_data_jalan');

Route::get('/data-irigasi-by-kecamatan', 'ApiForDashboardController@data_irigasi_by_kecamatan');
Route::get('/all-data-irigasi', 'ApiForDashboardController@all_data_irigasi');
Route::get('/data-irigasi-total', 'ApiForDashboardController@data_irigasi_total');

Route::get('/data-jembatan-per-kecamatan', 'ApiForDashboardController@data_jembatan_per_kecamatan');
Route::get('/data-jembatan-all', 'ApiForDashboardController@data_jembatan_all');
Route::get('/data-jembatan-count', 'ApiForDashboardController@data_jembatan_count');

Route::get('/data-situ-count', 'ApiForDashboardController@data_situ_count');
Route::get('/data-situ-all', 'ApiForDashboardController@data_situ_all');
Route::get('/data-situ-per-kecamatan', 'ApiForDashboardController@data_situ_per_kecamatan');

Route::get('/data-sungai-count', 'ApiForDashboardController@data_sungai_count');
Route::get('/data-sungai-all', 'ApiForDashboardController@data_sungai_all');
Route::get('/data-sungai-per-kali', 'ApiForDashboardController@data_sungai_per_kali');
Route::get('/data-sungai-per-kecamatan', 'ApiForDashboardController@data_sungai_per_kecamatan');
Route::get('/data-sungai-per-jenis', 'ApiForDashboardController@data_sungai_per_jenis');

Route::get('welcome', 'HomeController@welcome')->name('utama');
Route::get('/', 'Frontend\DashboardController@index')->name('utama');

Route::get('hasil-usulan', 'UsulanVerifikasiController@usulan')->name('hasil.usulan');
Route::get('datairigasi', 'DataSituController@datairigasi')->name('hasil.usulan');

Route::get('hasil-verifikasi', 'UsulanVerifikasiController@verifikasi')->name('hasil.verifikasi');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/readcsv', 'RumahkumuhController@readcsv')->name('home');

Route::get('dashboard', 'Backend\DashboardController')->name('dashboard')->middleware('auth');

Route::get('user-management', 'Backend\UserManagementController')->name('user.management')->middleware('auth');

Route::resource('usulan', 'Backend\UsulanController')->middleware('auth');

Route::get('usulan/{id}/delete', 'Backend\UsulanController@delete')->middleware('auth');

Route::get('data-kumuh/{kecamatan}','RumahkumuhController@datakumuh')->name('datakumuh.kecamatan');
Route::get('data-jalan/{kecamatan}','DataJalanController@jumlahruasjalan')->name('datajalan.kecamatan');
Route::get('detail-data/{kecamatan}','DataJalanController@datajalan')->name('detail.jalan');
Route::get('detail-ruas-jalan/{ruas}','DataJalanController@dataruasjalan')->name('detail.ruas');
Route::get('load_data', 'DataJalanController@load_data')->name('load.data');
Route::get('load-map/{id}', 'DataJalanController@load_maps')->name('load.map');
Route::get('json_kml_jalan', 'DataJalanController@json_kml_jalan')->name('load.json_kml_jalan');
Route::post('upload_kml', 'DataJalanController@upload_kml')->name('upload_kml');

Route::get('detail-data-irigasi/{kecamatan}','DataIrigasiController@datairigasi')->name('detail.irigasi');
Route::get('detail-data-situ/{kecamatan}','DataSituController@datasitu')->name('detail.situ');
Route::get('detail-data-jembatan/{kecamatan}','DataJembatanController@datajembatan')->name('detail.jembatan');
Route::get('detail-data-sungai/{kecamatan}','DataSungaiController@datasungai')->name('detail.sungai');
Route::get('cek-jembatan','DataJembatanController@cek');

Route::resource('verifikasi', 'Backend\VerifiedController')->middleware('auth');

Route::get('verifikasi/{id}/delete', 'Backend\VerifiedController@delete')->middleware('auth');

Route::get('data-kumuh-json','RumahkumuhController@datakumuhjson')->name('datakumuhjson.kecamatan');

Route::get('detail-data-kumuh/{kecamatan}','RumahkumuhController@detail')->name('detail.kecamatan');

Route::get('detail-data-kumuh-kelurahan/{kecamatan}/{kelurahan}','RumahkumuhController@detailkelurahan')->name('detail.kelurahan');

Route::get('kategori-admin','TrxBeritaKategoriController@index')->middleware('auth');

Route::resource('berita-admin','TrxBeritaController',[ 'only' => ['index', 'create', 'store','edit'] ])->middleware('auth');

Route::resource('berita','Frontend\BeritaController',[ 'only' => ['index', 'show'] ]);

Route::get('show/{slug}','Frontend\BeritaController@detail');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     //\UniSharp\LaravelFilemanager\Lfm::routes();
 });

Route::resource('all-data-jalan', 'BackendDataJalanController')->middleware('auth');
Route::get('all-data-jalan/delete/{id}', 'BackendDataJalanController@destroy')->middleware('auth');
Route::get('data-jalan-kondisi/{id}', 'BackendDataJalanController@kondisi');

Route::resource('all-irigasi', 'BackendIrigasiController')->middleware('auth');
Route::get('all-irigasi/delete/{id}', 'BackendIrigasiController@destroy')->middleware('auth');

Route::resource('all-situ', 'BackendSituController')->middleware('auth');
Route::get('all-situ/delete/{id}', 'BackendSituController@destroy')->middleware('auth');

Route::resource('all-sungai', 'BackendSungaiController')->middleware('auth');
Route::get('all-sungai/delete/{id}', 'BackendSungaiController@destroy')->middleware('auth');

Route::resource('all-jembatan', 'BackendJembatanController')->middleware('auth');
Route::get('all-jembatan/delete/{id}', 'BackendJembatanController@destroy')->middleware('auth');

Route::get('download-file/{jenis}','Backend\DashboardController@download_file')->middleware('auth');

Route::get('view-tabular-jalan', 'DataJalanController@view_tabular_jalan')->name('view_tabular_jalan');
Route::get('view-tabular-irigasi', 'DataIrigasiController@view_tabular_irigasi')->name('view_tabular_irigasi');
Route::get('view-tabular-situ', 'DataSituController@view_tabular_situ')->name('view_tabular_situ');
Route::get('view-tabular-sungai', 'DataSungaiController@view_tabular_sungai')->name('view_tabular_sungai');
Route::get('view-tabular-jembatan', 'DataJembatanController@view_tabular_jembatan')->name('view_tabular_jembatan');

resources/views/backend/pages/jalan/create.blade.php
@extends('backend.layouts.master')

@section('title')
    <title>Sistem Informasi Data Jalan - Admin Dashboard</title>
    <link rel="stylesheet" href="{{ asset('theme') }}/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ asset('theme') }}/css/dataTables.bootstrap.min.css">
    <style>
        td {
            font-size:12px;
        }
    </style>
@endsection

@section('content-head')
    <div id="for-alert"></div>

    @if (Session::has('message'))
        <div class='alert alert-success alert-style'>
            <strong>Ou yeah,</strong> {{ Session::get('message') }}
        </div>
    @endif

    @if ($errors->any())
        <div class='alert alert-danger alert-style'>
            <strong>Oops,</strong> Terjadi Kesalahan: <br>
            @foreach ($errors->all() as $item)
                <li>{{ $item }}</li>
            @endforeach
        </div>
    @endif
    

    <div class="profile-edit-page-header" style="margin-bottom:10px;">
        <h2>Manajemen Data Jalan</h2>
        <div class="breadcrumbs">
            <a href="{{ route('dashboard') }}">Home</a>
            <span>Manajemen Data Jalan</span>
        </div>
    </div>
@endsection

@section('content')
    
    <div class="col-md-12">
        <div class="dashboard-list-box fl-wrap">
            <div class="dashboard-header fl-wrap">
                <div class="box-title">
                    <h3>Formulir Input Data Jalan</h3>
                </div>
            </div>
            <div class="col-md-12" style="text-align:left;">
                <br>
                    <div class="profile-edit-container">
                        <form action="{{ route('all-data-jalan.store') }}" method="post" enctype="multipart/form-data">
                            @csrf

                            <div class="custom-form">

                                <label>Kecamatan<i class="fa fa-arrow-right"></i>  </label>
                                <select name="id_kecamatan" class="chosen-select" required>
                                    <option value="">-- Pilih --</option>
                                    @foreach ($kecamatan as $item)
                                        <option value="{{ $item->id }}">{{ $item->nama_kecamatan }}</option>
                                    @endforeach
                                </select>

                                <label>Nomor Ruas<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="no_ruas" required>

                                <label>Nama Jalan<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="nama_jalan" required>

                                <label>Volume Panjang (KM)<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="vol_panjang_km" required>

                                <label>Volume Lebar (M)<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="vol_lebar_m" required>

                                <label>Luas Jalan (M<sup>2</sup>)<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="luas_jalan_m_2" required>

                                <label>Konstruksi Beton<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="type_kons_beton" required>

                                <label>Konstruksi Aspal<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="type_kons_aspal" required>

                                <label>Konstruksi Lainnya<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="type_kons_dll" required>

                                <label>Keterangan<i class="fa fa-arrow-right"></i>  </label>
                                <select name="keterangan" class="chosen-select" required>
                                    <option value="">-- Pilih --</option>
                                    <option value="PR">PR</option>
                                    <option value="PKT">PKT</option>
                                    <option value="REHAB">REHAB</option>
                                    <option value="PP">PP</option>
                                </select>

                                <legend>
                                    Kondisi Jalan
                                </legend>

                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <td>#</td>
                                            <td>Baik</td>
                                            <td>Sedang</td>
                                            <td>Rusak</td>
                                            <td>Rusak Berat</td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>Beton</td>
                                            <td>
                                                <input type="text" name="kondisi_beton_b" style="padding-left:20px;" required>
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_beton_s" style="padding-left:20px;" required>
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_beton_r" style="padding-left:20px;" required>
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_beton_rb" style="padding-left:20px;" required>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Aspal</td>
                                            <td>
                                                <input type="text" name="kondisi_aspal_b" style="padding-left:20px;" required>
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_aspal_s" style="padding-left:20px;" required>
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_aspal_r" style="padding-left:20px;" required>
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_aspal_rb" style="padding-left:20px;" required>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Lainnya</td>
                                            <td>
                                                <input type="text" name="kondisi_lainnya_b" style="padding-left:20px;" required>
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_lainnya_s" style="padding-left:20px;" required>
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_lainnya_r" style="padding-left:20px;" required>
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_lainnya_rb" style="padding-left:20px;" required>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>

                                <label>Persentase Kerusakan<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="persentase_rusak" required>

                                <legend>
                                    Foto Ruas Jalan <i>(opsional)</i>
                                </legend>

                                <label>Foto Ruas Jalan 1</i>  </label>
                                <input type="file" name="foto_1" class="form-control">

                                <label>Foto Ruas Jalan 2</i>  </label>
                                <input type="file" name="foto_2" class="form-control">

                                <label>Foto Ruas Jalan 3</label>
                                <input type="file" name="foto_3" class="form-control">

                                <input type="submit" class="btn big-btn color-bg flat-btn" style="margin:20px 0;" value="Simpan Data">
                            </div>
                        </form>
                    </div>
                <br>
            </div>
        </div>
    </div>
@endsection

@section('modal')
    {{-- modal delete --}}
    <div class="main-register-wrap modal-delete">
        <div class="main-overlay"></div>
        <div class="main-register-holder">
            <div class="main-register fl-wrap">
                <div class="close-reg close-modal"><i class="fa fa-times"></i></div>
                <h3>Konfirmasi Penghapusan Data</h3>
                <p style="font-size:15px;">Apakah anda yakin akan menghapus data tersebut?</p>
                <a class="btn btn-danger close-modal" id="btn-delete">Ya, saya yakin.</a>
                <a class="btn btn-default close-modal">Tidak</a>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pages/jalan/edit.blade.php
@extends('backend.layouts.master')

@section('title')
    <title>Sistem Informasi Data Jalan - Admin Dashboard</title>
    <link rel="stylesheet" href="{{ asset('theme') }}/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ asset('theme') }}/css/dataTables.bootstrap.min.css">
    <style>
        td {
            font-size:12px;
        }
    </style>
@endsection

@section('content-head')
    <div id="for-alert"></div>

    @if (Session::has('message'))
        <div class='alert alert-success alert-style'>
            <strong>Ou yeah,</strong> {{ Session::get('message') }}
        </div>
    @endif

    @if ($errors->any())
        <div class='alert alert-danger alert-style'>
            <strong>Oops,</strong> Terjadi Kesalahan: <br>
            @foreach ($errors->all() as $item)
                <li>{{ $item }}</li>
            @endforeach
        </div>
    @endif
    

    <div class="profile-edit-page-header" style="margin-bottom:10px;">
        <h2>Manajemen Data Jalan</h2>
        <div class="breadcrumbs">
            <a href="{{ route('dashboard') }}">Home</a>
            <span>Manajemen Data Jalan</span>
        </div>
    </div>
@endsection

@section('content')
    
    <div class="col-md-12">
        <div class="dashboard-list-box fl-wrap">
            <div class="dashboard-header fl-wrap">
                <div class="box-title">
                    <h3>Formulir Edit Data Jalan</h3>
                </div>
            </div>
            <div class="col-md-12" style="text-align:left;">
                <br>
                    <div class="profile-edit-container">
                        <form action="{{ route('all-data-jalan.update', $data->id) }}" method="post" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="custom-form">

                                <label>Kecamatan<i class="fa fa-arrow-right"></i>  </label>
                                <select name="id_kecamatan" class="chosen-select">
                                    <option value="">-- Pilih --</option>
                                    @foreach ($kecamatan as $item)
                                        @if ($data->id_kecamatan==$item->id)
                                            <option value="{{ $item->id }}" selected>{{ $item->nama_kecamatan }}</option>
                                        @else
                                            <option value="{{ $item->id }}">{{ $item->nama_kecamatan }}</option>
                                        @endif
                                    @endforeach
                                </select>

                                <label>Nomor Ruas<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="no_ruas" value="{{ $data->no_ruas }}">

                                <label>Nama Jalan<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="nama_jalan" value="{{ $data->nama_jalan }}">

                                <label>Volume Panjang (KM)<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="vol_panjang_km" value="{{ $data->vol_panjang_km }}">

                                <label>Volume Lebar (M)<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="vol_lebar_m" value="{{ $data->vol_lebar_m }}">

                                <label>Luas Jalan (M<sup>2</sup>)<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="luas_jalan_m_2" value="{{ $data->luas_jalan_m_2 }}">

                                <label>Konstruksi Beton<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="type_kons_beton" value="{{ $data->type_kons_beton }}">

                                <label>Konstruksi Aspal<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="type_kons_aspal" value="{{ $data->type_kons_aspal }}">

                                <label>Konstruksi Lainnya<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="type_kons_dll" value="{{ $data->type_kons_dll }}">

                                <label>Keterangan<i class="fa fa-arrow-right"></i>  </label>
                                <select name="keterangan" class="chosen-select">
                                    <option value="">-- Pilih --</option>
                                    <option value="PR" {{ $data->keterangan=="PR" ? 'selected' : '' }}>PR</option>
                                    <option value="PKT" {{ $data->keterangan=="PKT" ? 'selected' : '' }}>PKT</option>
                                    <option value="REHAB" {{ $data->keterangan=="REHAB" ? 'selected' : '' }}>REHAB</option>
                                    <option value="PP" {{ $data->keterangan=="PP" ? 'selected' : '' }}>PP</option>
                                </select>

                                <legend>
                                    Kondisi Jalan
                                </legend>

                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <td>#</td>
                                            <td>Baik</td>
                                            <td>Sedang</td>
                                            <td>Rusak</td>
                                            <td>Rusak Berat</td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>Beton</td>
                                            <td>
                                                <input type="text" name="kondisi_beton_b" style="padding-left:20px;" value="{{ $beton['baik'] }}">
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_beton_s" style="padding-left:20px;" value="{{ $beton['sedang'] }}">
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_beton_r" style="padding-left:20px;" value="{{ $beton['rusak'] }}">
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_beton_rb" style="padding-left:20px;" value="{{ $beton['rusak_berat'] }}">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Aspal</td>
                                            <td>
                                                <input type="text" name="kondisi_aspal_b" style="padding-left:20px;" value="{{ $aspal['baik'] }}">
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_aspal_s" style="padding-left:20px;" value="{{ $aspal['sedang'] }}">
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_aspal_r" style="padding-left:20px;" value="{{ $aspal['rusak'] }}">
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_aspal_rb" style="padding-left:20px;" value="{{ $aspal['rusak_berat'] }}">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Lainnya</td>
                                            <td>
                                                <input type="text" name="kondisi_lainnya_b" style="padding-left:20px;" value="{{ $lainnya['baik'] }}">
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_lainnya_s" style="padding-left:20px;" value="{{ $lainnya['sedang'] }}">
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_lainnya_r" style="padding-left:20px;" value="{{ $lainnya['rusak'] }}">
                                            </td>
                                            <td>
                                                <input type="text" name="kondisi_lainnya_rb" style="padding-left:20px;" value="{{ $lainnya['rusak_berat'] }}">
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>

                                <label>Persentase Kerusakan<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="persentase_rusak" value="{{ $beton['persen'] }}">

                                <legend>
                                    Foto Ruas Jalan <i>(kosongkan jika tidak ingin diganti)</i>
                                </legend>

                                <label>Foto Ruas Jalan 1</i>  </label>
                                <img src="{{ asset('foto/jalan/') }}/{{ $data->foto_1 }}" alt="Foto tidak ditemukan." style="height:150px;margin-bottom:10px;">
                                <input type="file" name="foto_1" class="form-control">

                                <label>Foto Ruas Jalan 2</i>  </label>
                                <img src="{{ asset('foto/jalan/') }}/{{ $data->foto_2 }}" alt="Foto tidak ditemukan." style="height:150px;margin-bottom:10px;">
                                <input type="file" name="foto_2" class="form-control">

                                <label>Foto Ruas Jalan 3</label>
                                <img src="{{ asset('foto/jalan/') }}/{{ $data->foto_3 }}" alt="Foto tidak ditemukan." style="height:150px;margin-bottom:10px;">
                                <input type="file" name="foto_3" class="form-control">

                                <input type="submit" class="btn big-btn color-bg flat-btn" style="margin:20px 0;" value="Simpan Data">
                            </div>
                        </form>
                    </div>
                <br>
            </div>
        </div>
    </div>
@endsection

@section('modal')
    {{-- modal delete --}}
    <div class="main-register-wrap modal-delete">
        <div class="main-overlay"></div>
        <div class="main-register-holder">
            <div class="main-register fl-wrap">
                <div class="close-reg close-modal"><i class="fa fa-times"></i></div>
                <h3>Konfirmasi Penghapusan Data</h3>
                <p style="font-size:15px;">Apakah anda yakin akan menghapus data tersebut?</p>
                <a class="btn btn-danger close-modal" id="btn-delete">Ya, saya yakin.</a>
                <a class="btn btn-default close-modal">Tidak</a>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pages/jalan/map.blade.php
<div id="map"></div>
<script type="text/javascript">
    
      var map;
      function showMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 8
        });
      }

      showMap();
</script>

<style>
      #map {
        height: 500px;
      }
</style>