routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/jumlah-ruas-jalan', 'ApiForDashboardController@jumlah_ruas_jalan');
Route::get('/data-kondisi-jalan', 'ApiForDashboardController@data_kondisi_jalan');
Route::get('/total-konstruksi-jalan', 'ApiForDashboardController@total_konstruksi_jalan');
Route::get('/data-jalan-all', 'ApiForDashboardController@all_data_jalan');

Route::get('/data-irigasi-by-kecamatan', 'ApiForDashboardController@data_irigasi_by_kecamatan');
Route::get('/all-data-irigasi', 'ApiForDashboardController@all_data_irigasi');
Route::get('/data-irigasi-total', 'ApiForDashboardController@data_irigasi_total');

Route::get('/data-jembatan-per-kecamatan', 'ApiForDashboardController@data_jembatan_per_kecamatan');
Route::get('/data-jembatan-all', 'ApiForDashboardController@data_jembatan_all');
Route::get('/data-jembatan-count', 'ApiForDashboardController@data_jembatan_count');

Route::get('/data-situ-count', 'ApiForDashboardController@data_situ_count');
Route::get('/data-situ-all', 'ApiForDashboardController@data_situ_all');
Route::get('/data-situ-per-kecamatan', 'ApiForDashboardController@data_situ_per_kecamatan');

Route::get('/data-sungai-count', 'ApiForDashboardController@data_sungai_count');
Route::get('/data-sungai-all', 'ApiForDashboardController@data_sungai_all');
Route::get('/data-sungai-per-kali', 'ApiForDashboardController@data_sungai_per_kali');
Route::get('/data-sungai-per-kecamatan', 'ApiForDashboardController@data_sungai_per_kecamatan');
Route::get('/data-sungai-per-jenis', 'ApiForDashboardController@data_sungai_per_jenis');

Route::get('welcome', 'HomeController@welcome')->name('utama');
Route::get('/', 'Frontend\DashboardController@index')->name('utama');

Route::get('hasil-usulan', 'UsulanVerifikasiController@usulan')->name('hasil.usulan');
Route::get('datairigasi', 'DataSituController@datairigasi')->name('hasil.usulan');

Route::get('hasil-verifikasi', 'UsulanVerifikasiController@verifikasi')->name('hasil.verifikasi');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/readcsv', 'RumahkumuhController@readcsv')->name('home');

Route::get('dashboard', 'Backend\DashboardController')->name('dashboard')->middleware('auth');

Route::get('user-management', 'Backend\UserManagementController')->name('user.management')->middleware('auth');

Route::resource('usulan', 'Backend\UsulanController')->middleware('auth');

Route::get('usulan/{id}/delete', 'Backend\UsulanController@delete')->middleware('auth');

Route::get('data-kumuh/{kecamatan}','RumahkumuhController@datakumuh')->name('datakumuh.kecamatan');
Route::get('data-jalan/{kecamatan}','DataJalanController@jumlahruasjalan')->name('datajalan.kecamatan');
Route::get('detail-data/{kecamatan}','DataJalanController@datajalan')->name('detail.jalan');
Route::get('detail-ruas-jalan/{ruas}','DataJalanController@dataruasjalan')->name('detail.ruas');
Route::get('load_data', 'DataJalanController@load_data')->name('load.data');
Route::get('load-map/{id}', 'DataJalanController@load_maps')->name('load.map');
Route::get('json_kml_jalan', 'DataJalanController@json_kml_jalan')->name('load.json_kml_jalan');
Route::post('upload_kml', 'DataJalanController@upload_kml')->name('upload_kml');

Route::get('detail-data-irigasi/{kecamatan}','DataIrigasiController@datairigasi')->name('detail.irigasi');
Route::get('detail-data-situ/{kecamatan}','DataSituController@datasitu')->name('detail.situ');
Route::get('detail-data-jembatan/{kecamatan}','DataJembatanController@datajembatan')->name('detail.jembatan');
Route::get('detail-data-sungai/{kecamatan}','DataSungaiController@datasungai')->name('detail.sungai');
Route::get('cek-jembatan','DataJembatanController@cek');

Route::resource('verifikasi', 'Backend\VerifiedController')->middleware('auth');

Route::get('verifikasi/{id}/delete', 'Backend\VerifiedController@delete')->middleware('auth');

Route::get('data-kumuh-json','RumahkumuhController@datakumuhjson')->name('datakumuhjson.kecamatan');

Route::get('detail-data-kumuh/{kecamatan}','RumahkumuhController@detail')->name('detail.kecamatan');

Route::get('detail-data-kumuh-kelurahan/{kecamatan}/{kelurahan}','RumahkumuhController@detailkelurahan')->name('detail.kelurahan');

Route::get('kategori-admin','TrxBeritaKategoriController@index')->middleware('auth');

Route::resource('berita-admin','TrxBeritaController',[ 'only' => ['index', 'create', 'store','edit'] ])->middleware('auth');

Route::resource('berita','Frontend\BeritaController',[ 'only' => ['index', 'show'] ]);

Route::get('show/{slug}','Frontend\BeritaController@detail');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     //\UniSharp\LaravelFilemanager\Lfm::routes();
 });

Route::resource('all-data-jalan', 'BackendDataJalanController')->middleware('auth');
Route::get('all-data-jalan/delete/{id}', 'BackendDataJalanController@destroy')->middleware('auth');
Route::get('data-jalan-kondisi/{id}', 'BackendDataJalanController@kondisi');

Route::resource('all-irigasi', 'BackendIrigasiController')->middleware('auth');
Route::get('all-irigasi/delete/{id}', 'BackendIrigasiController@destroy')->middleware('auth');

Route::resource('all-situ', 'BackendSituController')->middleware('auth');
Route::get('all-situ/delete/{id}', 'BackendSituController@destroy')->middleware('auth');

Route::resource('all-sungai', 'BackendSungaiController')->middleware('auth');
Route::get('all-sungai/delete/{id}', 'BackendSungaiController@destroy')->middleware('auth');

Route::resource('all-jembatan', 'BackendJembatanController')->middleware('auth');
Route::get('all-jembatan/delete/{id}', 'BackendJembatanController@destroy')->middleware('auth');

Route::get('download-file/{jenis}','Backend\DashboardController@download_file')->middleware('auth');

Route::get('view-tabular-jalan', 'DataJalanController@view_tabular_jalan')->name('view_tabular_jalan');
Route::get('view-tabular-irigasi', 'DataIrigasiController@view_tabular_irigasi')->name('view_tabular_irigasi');
Route::get('view-tabular-situ', 'DataSituController@view_tabular_situ')->name('view_tabular_situ');
Route::get('view-tabular-sungai', 'DataSungaiController@view_tabular_sungai')->name('view_tabular_sungai');
Route::get('view-tabular-jembatan', 'DataJembatanController@view_tabular_jembatan')->name('view_tabular_jembatan');

app/Models/Usulan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Usulan extends Model
{
    use SoftDeletes;

    protected $table = 'trx_usulan';
    
    protected $fillable = [
        'id_kecamatan', 'no_bnba', 'penerima', 'alamat', 'jenis_kegiatan', 
        'dana_pk_rumah', 'dana_pemb_wc', 'dana_bop_keg', 'dana_total', 'status', 
        'id_upk_bkad', 'id_kpm', 'total_dana', 'total_unit_rtlh'
    ];

    public function kecamatan()
    {
        return $this->belongsTo('App\Models\Kecamatan', 'id_kecamatan');
    }

    public function verifikasi()
    {
        return $this->hasOne('App\Models\Verified', 'no_bnba');
    }
    
}

app/Http/Controllers/Backend/UsulanController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Kecamatan;
use App\Models\Usulan;
use App\Models\Upk_bkad;
use App\Models\Kpm_rt;

class UsulanController extends Controller
{
    public function index()
    {
        return view('backend.pages.usulan.index');
    }
    
    public function create()
    {
        $getkecamatan = Kecamatan::all();
        $getupk = Upk_bkad::all();
        $getkpm = Kpm_rt::all();

        return view('backend.pages.usulan.create')
            ->with('upk', $getupk)
            ->with('kpm', $getkpm)
            ->with('kecamatan', $getkecamatan);
    }

    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'id_kecamatan' => 'required',
            'no_bnba' => 'required',
            'penerima' => 'required',
            'alamat' => 'required',
            'jenis_kegiatan' => 'required',
            'dana_pk_rumah' => 'required|numeric',
            'dana_pemb_wc' => 'required|numeric',
            'dana_bop_keg' => 'required|numeric',
            'id_upk_bkad' => 'required',
            'id_kpm' => 'required',
        ]);

        $dana_total = $request->dana_pk_rumah + $request->dana_pemb_wc + $request->dana_bop_keg;

        $insert = Usulan::find($id);
        $insert->id_kecamatan = $request->id_kecamatan;
        $insert->no_bnba = $request->no_bnba;
        $insert->penerima = $request->penerima;
        $insert->alamat = $request->alamat;
        $insert->jenis_kegiatan = $request->jenis_kegiatan;
        $insert->dana_pk_rumah = $request->dana_pk_rumah;
        $insert->dana_pemb_wc = $request->dana_pemb_wc;
        $insert->dana_bop_keg = $request->dana_bop_keg;
        $insert->dana_total = $dana_total;
        $insert->id_upk_bkad = $request->id_upk_bkad;
        $insert->id_kpm = $request->id_kpm;
        $insert->total_dana = 0;
        $insert->total_unit_rtlh = 0;
        $insert->save();

        return redirect()->route('usulan.index')->with('message', 'berhasil mengupdate data usulan baru.');
    }

    public function edit($id)
    {
        $getusulan = Usulan::find($id);
        $getkecamatan = Kecamatan::all();
        $getupk = Upk_bkad::all();
        $getkpm = Kpm_rt::all();

        return view('backend.pages.usulan.edit')
            ->with('upk', $getupk)
            ->with('kpm', $getkpm)
            ->with('kecamatan', $getkecamatan)
            ->with('data', $getusulan);
    }

    public function store(Request $request)
    {
        $validate = $request->validate([
            'id_kecamatan' => 'required',
            'no_bnba' => 'required',
            'penerima' => 'required',
            'alamat' => 'required',
            'jenis_kegiatan' => 'required',
            'dana_pk_rumah' => 'required|numeric',
            'dana_pemb_wc' => 'required|numeric',
            'dana_bop_keg' => 'required|numeric',
            'id_upk_bkad' => 'required',
            'id_kpm' => 'required',
        ]);

        $dana_total = $request->dana_pk_rumah + $request->dana_pemb_wc + $request->dana_bop_keg;

        $insert = new Usulan;
        $insert->id_kecamatan = $request->id_kecamatan;
        $insert->no_bnba = $request->no_bnba;
        $insert->penerima = $request->penerima;
        $insert->alamat = $request->alamat;
        $insert->jenis_kegiatan = $request->jenis_kegiatan;
        $insert->dana_pk_rumah = $request->dana_pk_rumah;
        $insert->dana_pemb_wc = $request->dana_pemb_wc;
        $insert->dana_bop_keg = $request->dana_bop_keg;
        $insert->dana_total = $dana_total;
        $insert->id_upk_bkad = $request->id_upk_bkad;
        $insert->id_kpm = $request->id_kpm;
        $insert->total_dana = 0;
        $insert->total_unit_rtlh = 0;
        $insert->save();

        return redirect()->route('usulan.index')->with('message', 'berhasil memasukkan data usulan baru.');
    }

    public function delete($id)
    {
        Usulan::find($id)->delete();

        return redirect()->route('usulan.index')->with('message', 'berhasil menghapus data usulan.');
    }
}

resources/views/backend/pages/usulan/create.blade.php
@extends('backend.layouts.master')

@section('title')
    <title>ASIK - Admin Dashboard</title>
    <link rel="stylesheet" href="{{ asset('theme') }}/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ asset('theme') }}/css/dataTables.bootstrap.min.css">
    <style>
        .fa {
            margin-top: 5px;
        }

        .big-btn {
            margin-top: 10px !important;
            margin-bottom: 20px;
        }

        .big-btn:hover {
            color: #fff;
        }
    </style>
@endsection

@section('content-head')
    <div id="for-alert"></div>

    <div class="profile-edit-page-header" style="margin-bottom:10px;">
        <h2>Manajemen Data Usulan</h2>
        <div class="breadcrumbs">
            <a href="{{ route('dashboard') }}">Home</a>
            <a href="{{ route('usulan.index') }}">Manajemen Data Usulan</a>
            <span>Form Tambah Data Usulan</span>
        </div>
    </div>
@endsection

@section('content')
    
    <div class="col-md-12">
        <div class="dashboard-list-box fl-wrap">
            <div class="dashboard-header fl-wrap">
                <div class="box-title">
                    <h3>Data Usulan</h3>
                </div>
            </div>
            <div class="col-md-12" style="text-align:left;">
                <br>
                    <div class="profile-edit-container">
                        <form action="{{ route('usulan.store') }}" method="post">
                            @csrf
                            <div class="custom-form">
                                <label>Kecamatan <i class="fa fa-user-o"></i></label>
                                <select name="id_kecamatan" class="chosen-select">
                                    <option disabled selected>-- Seluruh Kecamatan --</option>
                                    @foreach ($kecamatan as $item)
                                        <option value="{{ $item->id }}">{{ $item->nama_kecamatan }}</option>
                                    @endforeach
                                </select>
                                <label>UPK BKAD<i class="fa fa-user-o"></i></label>
                                <select name="id_upk_bkad" class="chosen-select">
                                    <option disabled selected>-- Seluruh UPK BKAD --</option>
                                    @foreach ($upk as $item)
                                        <option value="{{ $item->id }}">{{ $item->nama }}</option>
                                    @endforeach
                                </select>
                                <label>KPM RT<i class="fa fa-user-o"></i></label>
                                <select name="id_kpm" class="chosen-select">
                                    <option disabled selected>-- Seluruh KPM RT --</option>
                                    @foreach ($kpm as $item)
                                        <option value="{{ $item->id }}">{{ $item->nama }}</option>
                                    @endforeach
                                </select>
                                <label>Nomor BNBA<i class="fa fa-list"></i>  </label>
                                <input type="text" name="no_bnba">
                                <label>Penerima<i class="fa fa-user"></i>  </label>
                                <input type="text" name="penerima">
                                <label>Alamat<i class="fa fa-map-marker"></i>  </label>
                                <input type="text" name="alamat">
                                <label>Jenis Kegiatan<i class="fa fa-globe"></i>  </label>
                                <input type="text" name="jenis_kegiatan">
                                <label>Dana PK Rumah<i class="fa fa-home"></i>  </label>
                                <input type="text" name="dana_pk_rumah">
                                <label>Dana Pembangunan WC<i class="fa fa-home"></i>  </label>
                                <input type="text" name="dana_pemb_wc">
                                <label>Dana BOP Kegiatan<i class="fa fa-home"></i>  </label>
                                <input type="text" name="dana_bop_keg">

                                <button class="btn big-btn color-bg flat-btn">Save Changes<i class="fa fa-angle-right"></i></button>
                            </div>
                        </form>
                    </div>
                <br>
            </div>
        </div>
    </div>
@endsection

@section('modal')
    {{-- modal delete --}}
    <div class="main-register-wrap modal-delete">
        <div class="main-overlay"></div>
        <div class="main-register-holder">
            <div class="main-register fl-wrap">
                <div class="close-reg close-modal"><i class="fa fa-times"></i></div>
                <h3>Konfirmasi Penghapusan Data</h3>
                <p style="font-size:15px;">Apakah anda yakin akan menghapus data tersebut?</p>
                <a class="btn btn-danger close-modal" id="btn-delete">Ya, saya yakin.</a>
                <a class="btn btn-default close-modal">Tidak</a>
            </div>
        </div>
    </div>
@endsection

@section('foot-script')
    <script>
        
    </script>
@endsection

resources/views/backend/pages/usulan/edit.blade.php
@extends('backend.layouts.master')

@section('title')
    <title>ASIK - Admin Dashboard</title>
    <link rel="stylesheet" href="{{ asset('theme') }}/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ asset('theme') }}/css/dataTables.bootstrap.min.css">
    <style>
        .fa {
            margin-top: 5px;
        }

        .big-btn {
            margin-top: 10px !important;
            margin-bottom: 20px;
        }

        .big-btn:hover {
            color: #fff;
        }
    </style>
@endsection

@section('content-head')
    <div id="for-alert"></div>

    <div class="profile-edit-page-header" style="margin-bottom:10px;">
        <h2>Manajemen Data Usulan</h2>
        <div class="breadcrumbs">
            <a href="{{ route('dashboard') }}">Home</a>
            <a href="{{ route('usulan.index') }}">Manajemen Data Usulan</a>
            <span>Edit Data Usulan</span>
        </div>
    </div>
@endsection

@section('content')
    
    <div class="col-md-12">
        <div class="dashboard-list-box fl-wrap">
            <div class="dashboard-header fl-wrap">
                <div class="box-title">
                    <h3>Data Usulan</h3>
                </div>
            </div>
            <div class="col-md-12" style="text-align:left;">
                <br>
                    <div class="profile-edit-container">
                        <form action="{{ route('usulan.update', $data->id) }}" method="post">
                            @csrf
                            @method('PUT')
                            <div class="custom-form">
                                <label>Kecamatan <i class="fa fa-user-o"></i></label>
                                <select name="id_kecamatan" class="chosen-select">
                                    <option disabled selected>-- Seluruh Kecamatan --</option>
                                    @foreach ($kecamatan as $item)
                                        @if ($data->id_kecamatan==$item->id)
                                            <option value="{{ $item->id }}" selected>{{ $item->nama_kecamatan }}</option>
                                        @endif
                                        <option value="{{ $item->id }}">{{ $item->nama_kecamatan }}</option>
                                    @endforeach
                                </select>
                                <label>UPK BKAD<i class="fa fa-user-o"></i></label>
                                <select name="id_upk_bkad" class="chosen-select">
                                    <option disabled selected>-- Seluruh UPK BKAD --</option>
                                    @foreach ($upk as $item)
                                        @if ($data->id_upk_bkad==$item->id)
                                            <option value="{{ $item->id }}" selected>{{ $item->nama }}</option>
                                        @endif
                                        <option value="{{ $item->id }}">{{ $item->nama }}</option>
                                    @endforeach
                                </select>
                                <label>KPM RT<i class="fa fa-user-o"></i></label>
                                <select name="id_kpm" class="chosen-select">
                                    <option disabled selected>-- Seluruh KPM RT --</option>
                                    @foreach ($kpm as $item)
                                        @if ($data->id_kpm==$item->id)
                                            <option value="{{ $item->id }}" selected>{{ $item->nama }}</option>
                                        @endif
                                        <option value="{{ $item->id }}">{{ $item->nama }}</option>
                                    @endforeach
                                </select>
                                <label>Nomor BNBA<i class="fa fa-list"></i>  </label>
                                <input type="text" name="no_bnba" value="{{ $data->no_bnba }}">
                                <label>Penerima<i class="fa fa-user"></i>  </label>
                                <input type="text" name="penerima" value="{{ $data->penerima }}">
                                <label>Alamat<i class="fa fa-map-marker"></i>  </label>
                                <input type="text" name="alamat" value="{{ $data->alamat }}">
                                <label>Jenis Kegiatan<i class="fa fa-globe"></i>  </label>
                                <input type="text" name="jenis_kegiatan" value="{{ $data->jenis_kegiatan }}">
                                <label>Dana PK Rumah<i class="fa fa-home"></i>  </label>
                                <input type="text" name="dana_pk_rumah" value="{{ $data->dana_pk_rumah }}">
                                <label>Dana Pembangunan WC<i class="fa fa-home"></i>  </label>
                                <input type="text" name="dana_pemb_wc" value="{{ $data->dana_pemb_wc }}">
                                <label>Dana BOP Kegiatan<i class="fa fa-home"></i>  </label>
                                <input type="text" name="dana_bop_keg" value="{{ $data->dana_bop_keg }}">

                                <button class="btn big-btn color-bg flat-btn">Save Changes<i class="fa fa-angle-right"></i></button>
                            </div>
                        </form>
                    </div>
                <br>
            </div>
        </div>
    </div>
@endsection

@section('modal')
    {{-- modal delete --}}
    <div class="main-register-wrap modal-delete">
        <div class="main-overlay"></div>
        <div class="main-register-holder">
            <div class="main-register fl-wrap">
                <div class="close-reg close-modal"><i class="fa fa-times"></i></div>
                <h3>Konfirmasi Penghapusan Data</h3>
                <p style="font-size:15px;">Apakah anda yakin akan menghapus data tersebut?</p>
                <a class="btn btn-danger close-modal" id="btn-delete">Ya, saya yakin.</a>
                <a class="btn btn-default close-modal">Tidak</a>
            </div>
        </div>
    </div>
@endsection

@section('foot-script')
    <script>
        
    </script>
@endsection

resources/views/backend/pages/usulan/index.blade.php
@extends('backend.layouts.master')

@section('title')
    <title>ASIK - Admin Dashboard</title>
    <link rel="stylesheet" href="{{ asset('theme') }}/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ asset('theme') }}/css/dataTables.bootstrap.min.css">
@endsection

@section('content-head')
    <div id="for-alert"></div>

    @if (Session::has('message'))
        <div class='alert alert-success alert-style'>
            <strong>Ou yeah,</strong> {{ Session::get('message') }}
        </div>
    @endif

    <div class="profile-edit-page-header" style="margin-bottom:10px;">
        <h2>Manajemen Data Usulan</h2>
        <div class="breadcrumbs">
            <a href="{{ route('dashboard') }}">Home</a>
            <span>Manajemen Data Usulan</span>
        </div>
    </div>
@endsection

@section('content')
    
    <div class="col-md-12">
        <div class="dashboard-list-box fl-wrap">
            <div class="dashboard-header fl-wrap">
                <div class="box-title">
                    <h3>Data Usulan</h3>
                </div>
                <div style="float:right;width:100px;">
                    <a href="{{ route('usulan.create') }}" class="btn btn-success btn-sm">+ Tambah Data</a>
                </div>
            </div>
            <div class="col-md-12" style="text-align:left;">
                <br>
                <table id="user-table" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th style="width:15px;" rowspan="2">#</th>
                            <th rowspan="2">Kecamatan</th>
                            <th rowspan="2">BNBA</th>
                            <th rowspan="2">Penerima</th>
                            <th rowspan="2">Alamat</th>
                            <th rowspan="2">Kegiatan</th>
                            <th colspan="3">Alokasi Dana</th>
                            <th rowspan="2">Aksi</th>
                        </tr>
                        <tr>
                            <td>Rumah</td>
                            <td>WC</td>
                            <td>BOP</td>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                <br>
            </div>
        </div>
    </div>
@endsection

@section('modal')
    {{-- modal delete --}}
    <div class="main-register-wrap modal-delete">
        <div class="main-overlay"></div>
        <div class="main-register-holder">
            <div class="main-register fl-wrap">
                <div class="close-reg close-modal"><i class="fa fa-times"></i></div>
                <h3>Konfirmasi Penghapusan Data</h3>
                <p style="font-size:15px;">Apakah anda yakin akan menghapus data tersebut?</p>
                <a class="btn btn-danger close-modal" id="btn-delete">Ya, saya yakin.</a>
                <a class="btn btn-default close-modal">Tidak</a>
            </div>
        </div>
    </div>
@endsection

@section('foot-script')
    <script src="{{ asset('theme') }}/js/jquery.dataTables.min.js"></script>
    <script src="{{ asset('theme') }}/js/dataTables.bootstrap.min.js"></script>
    
    <script>
        $(function() {
            $('#user-table').DataTable();
            populateTable()
        });

        // show confirmation modal delete
        $('#user-table').on('click', '.modal-open-delete', function(e){
            e.preventDefault();
            $('.modal-delete').fadeIn();
            $("html, body").addClass("hid-body");

            var id = $(this).data('value')
            $('#btn-delete').attr('href', "{{ url('usulan') }}/"+id+"/delete")
        })

        // populate table funciton
        function populateTable() {
            var no = 1;
            $.ajax({
                url: "{{ url('api/usulan-api') }}" ,
                success: function(res) {
                    $('#user-table').dataTable({
                        "aaData": res.data,
                        "bDestroy": true,
                        "columns": [
                            { "data" : "id" },
                            { "data" : "kecamatan.nama_kecamatan" },
                            { "data" : "no_bnba" },
                            { "data" : "penerima" },
                            { "data" : "alamat" },
                            { "data" : "jenis_kegiatan" },
                            { "data" : "dana_pk_rumah" },
                            { "data" : "dana_pemb_wc" },
                            { "data" : "dana_bop_keg" },
                        ],
                        "columnDefs": [ {
                            "targets"   : 9,
                            "data"      : "id",
                            "render"    : function (item) {
                                return  "<a class='btn btn-xs btn-warning' href='{{ url('usulan') }}/"+item+"/edit'>" +
                                            "<span class='fa fa-edit'></span>" +
                                        "</a> " +
                                        "<a class='btn btn-xs btn-danger modal-open-delete' data-value='"+ item +"'>" +
                                            "<span class='fa fa-trash'></span>" +
                                        "</a>"
                            }
                        } ]
                    })
                }   
            })
        }
    </script>
@endsection