routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/jumlah-ruas-jalan', 'ApiForDashboardController@jumlah_ruas_jalan');
Route::get('/data-kondisi-jalan', 'ApiForDashboardController@data_kondisi_jalan');
Route::get('/total-konstruksi-jalan', 'ApiForDashboardController@total_konstruksi_jalan');
Route::get('/data-jalan-all', 'ApiForDashboardController@all_data_jalan');

Route::get('/data-irigasi-by-kecamatan', 'ApiForDashboardController@data_irigasi_by_kecamatan');
Route::get('/all-data-irigasi', 'ApiForDashboardController@all_data_irigasi');
Route::get('/data-irigasi-total', 'ApiForDashboardController@data_irigasi_total');

Route::get('/data-jembatan-per-kecamatan', 'ApiForDashboardController@data_jembatan_per_kecamatan');
Route::get('/data-jembatan-all', 'ApiForDashboardController@data_jembatan_all');
Route::get('/data-jembatan-count', 'ApiForDashboardController@data_jembatan_count');

Route::get('/data-situ-count', 'ApiForDashboardController@data_situ_count');
Route::get('/data-situ-all', 'ApiForDashboardController@data_situ_all');
Route::get('/data-situ-per-kecamatan', 'ApiForDashboardController@data_situ_per_kecamatan');

Route::get('/data-sungai-count', 'ApiForDashboardController@data_sungai_count');
Route::get('/data-sungai-all', 'ApiForDashboardController@data_sungai_all');
Route::get('/data-sungai-per-kali', 'ApiForDashboardController@data_sungai_per_kali');
Route::get('/data-sungai-per-kecamatan', 'ApiForDashboardController@data_sungai_per_kecamatan');
Route::get('/data-sungai-per-jenis', 'ApiForDashboardController@data_sungai_per_jenis');

Route::get('welcome', 'HomeController@welcome')->name('utama');
Route::get('/', 'Frontend\DashboardController@index')->name('utama');

Route::get('hasil-usulan', 'UsulanVerifikasiController@usulan')->name('hasil.usulan');
Route::get('datairigasi', 'DataSituController@datairigasi')->name('hasil.usulan');

Route::get('hasil-verifikasi', 'UsulanVerifikasiController@verifikasi')->name('hasil.verifikasi');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/readcsv', 'RumahkumuhController@readcsv')->name('home');

Route::get('dashboard', 'Backend\DashboardController')->name('dashboard')->middleware('auth');

Route::get('user-management', 'Backend\UserManagementController')->name('user.management')->middleware('auth');

Route::resource('usulan', 'Backend\UsulanController')->middleware('auth');

Route::get('usulan/{id}/delete', 'Backend\UsulanController@delete')->middleware('auth');

Route::get('data-kumuh/{kecamatan}','RumahkumuhController@datakumuh')->name('datakumuh.kecamatan');
Route::get('data-jalan/{kecamatan}','DataJalanController@jumlahruasjalan')->name('datajalan.kecamatan');
Route::get('detail-data/{kecamatan}','DataJalanController@datajalan')->name('detail.jalan');
Route::get('detail-ruas-jalan/{ruas}','DataJalanController@dataruasjalan')->name('detail.ruas');
Route::get('load_data', 'DataJalanController@load_data')->name('load.data');
Route::get('load-map/{id}', 'DataJalanController@load_maps')->name('load.map');
Route::get('json_kml_jalan', 'DataJalanController@json_kml_jalan')->name('load.json_kml_jalan');
Route::post('upload_kml', 'DataJalanController@upload_kml')->name('upload_kml');

Route::get('detail-data-irigasi/{kecamatan}','DataIrigasiController@datairigasi')->name('detail.irigasi');
Route::get('detail-data-situ/{kecamatan}','DataSituController@datasitu')->name('detail.situ');
Route::get('detail-data-jembatan/{kecamatan}','DataJembatanController@datajembatan')->name('detail.jembatan');
Route::get('detail-data-sungai/{kecamatan}','DataSungaiController@datasungai')->name('detail.sungai');
Route::get('cek-jembatan','DataJembatanController@cek');

Route::resource('verifikasi', 'Backend\VerifiedController')->middleware('auth');

Route::get('verifikasi/{id}/delete', 'Backend\VerifiedController@delete')->middleware('auth');

Route::get('data-kumuh-json','RumahkumuhController@datakumuhjson')->name('datakumuhjson.kecamatan');

Route::get('detail-data-kumuh/{kecamatan}','RumahkumuhController@detail')->name('detail.kecamatan');

Route::get('detail-data-kumuh-kelurahan/{kecamatan}/{kelurahan}','RumahkumuhController@detailkelurahan')->name('detail.kelurahan');

Route::get('kategori-admin','TrxBeritaKategoriController@index')->middleware('auth');

Route::resource('berita-admin','TrxBeritaController',[ 'only' => ['index', 'create', 'store','edit'] ])->middleware('auth');

Route::resource('berita','Frontend\BeritaController',[ 'only' => ['index', 'show'] ]);

Route::get('show/{slug}','Frontend\BeritaController@detail');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     //\UniSharp\LaravelFilemanager\Lfm::routes();
 });

Route::resource('all-data-jalan', 'BackendDataJalanController')->middleware('auth');
Route::get('all-data-jalan/delete/{id}', 'BackendDataJalanController@destroy')->middleware('auth');
Route::get('data-jalan-kondisi/{id}', 'BackendDataJalanController@kondisi');

Route::resource('all-irigasi', 'BackendIrigasiController')->middleware('auth');
Route::get('all-irigasi/delete/{id}', 'BackendIrigasiController@destroy')->middleware('auth');

Route::resource('all-situ', 'BackendSituController')->middleware('auth');
Route::get('all-situ/delete/{id}', 'BackendSituController@destroy')->middleware('auth');

Route::resource('all-sungai', 'BackendSungaiController')->middleware('auth');
Route::get('all-sungai/delete/{id}', 'BackendSungaiController@destroy')->middleware('auth');

Route::resource('all-jembatan', 'BackendJembatanController')->middleware('auth');
Route::get('all-jembatan/delete/{id}', 'BackendJembatanController@destroy')->middleware('auth');

Route::get('download-file/{jenis}','Backend\DashboardController@download_file')->middleware('auth');

Route::get('view-tabular-jalan', 'DataJalanController@view_tabular_jalan')->name('view_tabular_jalan');
Route::get('view-tabular-irigasi', 'DataIrigasiController@view_tabular_irigasi')->name('view_tabular_irigasi');
Route::get('view-tabular-situ', 'DataSituController@view_tabular_situ')->name('view_tabular_situ');
Route::get('view-tabular-sungai', 'DataSungaiController@view_tabular_sungai')->name('view_tabular_sungai');
Route::get('view-tabular-jembatan', 'DataJembatanController@view_tabular_jembatan')->name('view_tabular_jembatan');

app/Http/Controllers/Frontend/BeritaController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Rumahkumuh;
use App\Models\TrxBerita;
class BeritaController extends Controller
{
    public function index()
    {
        $berita=TrxBerita::orderBy('created_at','desc')->get();
        return view('frontend.pages.berita.index')->with('berita',$berita);
    }
    public function show($id)
    {
        $berita=TrxBerita::where('slug','like',$id)->first();
        $populer=TrxBerita::where('id','!=',$berita->id)->orderBy('view','desc')->orderBy('created_at','desc')->limit(5)->get();
        return view('frontend.pages.berita.detail')
            ->with('berita',$berita)
            ->with('populer',$populer);
    }

    public function detail($slug)
    {
        $berita=TrxBerita::where('slug','like',$slug)->first();
        $berita->view=($berita->view +1);
        $berita->save();

        return redirect('berita/'.$slug);
    }
}

resources/views/backend/pages/berita/create.blade.php
@extends('backend.layouts.master')

@section('title')
    <title>Sistem Informasi Data Jalan - Admin Dashboard</title>
    <link rel="stylesheet" href="{{ asset('theme') }}/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ asset('theme') }}/css/dataTables.bootstrap.min.css">
    <style>
        .fa {
            margin-top: 5px;
        }

        .big-btn {
            margin-top: 10px !important;
            margin-bottom: 20px;
        }

        .big-btn:hover {
            color: #fff;
        }
    </style>
@endsection

@section('content-head')
    <div id="for-alert"></div>

    <div class="profile-edit-page-header" style="margin-bottom:10px;">
        <h2>Manajemen Data Berita</h2>
        <div class="breadcrumbs">
            <a href="{{ route('dashboard') }}">Home</a>
            <a href="{{ url('berita-admin') }}">Manajemen Data Berita</a>
            <span>Form Tambah Data Berita</span>
        </div>
    </div>
@endsection

@section('content')
    
    <div class="col-md-12">
        <div class="dashboard-list-box fl-wrap">
            <div class="dashboard-header fl-wrap">
                <div class="box-title">
                    <h3>Data Berita</h3>
                </div>
            </div>
            <div class="col-md-12" style="text-align:left;">
                <br>
                    <div class="profile-edit-container">
                        <form action="{{ url('api/berita-management') }}" method="post" id="simpan-berita">
                            @csrf
                            <div class="custom-form">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Kategori <i class="fa fa-user-o"></i></label>
                                        <select name="id_kategori" id="id_kategori" class="chosen-select">
                                            <option selected value="-1">-- Kategori --</option>
                                            @foreach ($kategori as $item)
                                                <option value="{{ $item->id }}">{{ $item->nama_kategori }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-md-6">
                                        <label>Judul <i class="fa fa-list"></i>  </label>
                                        <input type="text" name="title" id="title">
                                    </div>
                                </div>
                                <input type="hidden" name="id_user" id="user_id" value="{{Auth::user()->id}}">
                                <div class="row">
                                    <div class="col-md-4">
                                        <label>Cover <i class="fa fa-image"></i>  </label>
                                        <input type="text" name="file" id="thumbnail" readonly>
                                    </div>
                                    <div class="col-md-1">
                                        <label>&nbsp;</label>
                                        <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn big-btn color-bg flat-btn" style="margin-top:0px !important;">
                                            <i class="fa fa-search"></i> Choose
                                        </a>
                                    </div>
                                    <div class="col-md-1">&nbsp;</div>
                                    <div class="col-md-6">
                                        <label>Status <i class="fa fa-user-o"></i></label>
                                        <select name="flag" id="flag" class="chosen-select">
                                            <option selected value="-1">-- Status Berita --</option>
                                            <option value="1">Aktif</option>
                                            <option value="0">Tidak Aktif</option>
                                            
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <img id="holder" style="margin-top:15px;max-height:100px;">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <label>Isi Berita</label>
                                    </div>
                                    <div class="col-md-12">
                                        <textarea type="text" name="desc" id="desc"></textarea>
                                    </div>
                                </div>
                                

                                <button class="btn big-btn color-bg flat-btn" type="button" id="simpan">Save Changes<i class="fa fa-angle-right"></i></button>
                            </div>
                        </form>
                    </div>
                <br>
            </div>
        </div>
    </div>
@endsection

@section('modal')
    {{-- modal delete --}}
    <div class="main-register-wrap modal-delete">
        <div class="main-overlay"></div>
        <div class="main-register-holder">
            <div class="main-register fl-wrap">
                <div class="close-reg close-modal"><i class="fa fa-times"></i></div>
                <h3>Konfirmasi Penghapusan Data</h3>
                <p style="font-size:15px;">Apakah anda yakin akan menghapus data tersebut?</p>
                <a class="btn btn-danger close-modal" id="btn-delete">Ya, saya yakin.</a>
                <a class="btn btn-default close-modal">Tidak</a>
            </div>
        </div>
    </div>
@endsection
<div class="main-register-wrap modal-kesalahan">
        <div class="main-overlay"></div>
        <div class="main-register-holder">
            <div class="main-register fl-wrap">
                <div class="close-reg close-modal"><i class="fa fa-times" style="margin-top:10px !important;"></i></div>
                <h3>Kesalahan</h3>
                <p style="font-size:25px;" id="pesan"></p>
                <a class="btn btn-default close-modal">OK</a>
            </div>
        </div>
    </div>
<div class="main-register-wrap modal-simpan">
        <div class="main-overlay"></div>
        <div class="main-register-holder">
            <div class="main-register fl-wrap">
                <div class="close-reg close-modal"><i class="fa fa-times" style="margin-top:10px !important"></i></div>
                <h3>Konfirmasi Simpan Data</h3>
                <p style="font-size:15px;">Apakah anda yakin akan menyimpan data ini?</p>
                <a class="btn btn-success" id="btn-simpan">Ya, saya yakin.</a>
                <a class="btn btn-default close-modal">Tidak</a>
            </div>
        </div>
    </div>
@section('foot-script')
    <script type="text/javascript" src="{{ asset('js/ckeditor/ckeditor.js')}}"></script>
    <script src="{{asset('/vendor/laravel-filemanager/js/lfm.js')}}"></script>
    <script>
        $(document).ready(function(){
            $('.close-modal').on('click',function(){
                $('.modal-kesalahan').fadeOut();
                $('.modal-simpan').fadeOut();
            });
            $('#lfm').filemanager('image', {prefix: '{{url("/")}}/laravel-filemanager'});
      
			var options = {
				filebrowserImageBrowseUrl: '{{url("/")}}/laravel-filemanager?type=Images',
				filebrowserImageUploadUrl: '{{url("/")}}/laravel-filemanager/upload?type=Images&_token=',
				filebrowserBrowseUrl: '{{url("/")}}/laravel-filemanager?type=Files',
				filebrowserUploadUrl: 	'{{url("/")}}/laravel-filemanager/upload?type=Files&_token='
			};
            CKEDITOR.replace('desc', options);
            
            
        });
        $('#simpan').on('click',function(e){
                var id_kategori=$('#id_kategori').val();
                var title=$('#title').val();
                var thumbnail=$('#thumbnail').val();
                var desc = CKEDITOR.instances['desc'].getData();
                // var desc=$('#desc').val();
                var user_id=$('#user_id').val();
                if(id_kategori=='-1')
                {
                    $('#pesan').text('Anda Belum Memilih Kategori');
                    $('.modal-kesalahan').fadeIn();
                }
                else if(title=='')
                {
                    $('#pesan').text('Anda Belum Mengisi Judul');
                    $('.modal-kesalahan').fadeIn();
                }
                else
                {
                    //e.preventDefault();
                    $('.modal-simpan').fadeIn();
                    // $("html, body").addClass("hid-body");
                }
                    
            });

            $('#btn-simpan').on('click',function(){
                // $('.modal-simpan').fadeOut();
                $('#simpan-berita').submit();
            });
    </script>
@endsection

resources/views/backend/pages/berita/index.blade.php
@extends('backend.layouts.master')

@section('title')
    <title>Sistem Informasi Data Jalan - Admin Dashboard</title>
    <link rel="stylesheet" href="{{ asset('theme') }}/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ asset('theme') }}/css/dataTables.bootstrap.min.css">
@endsection

@section('content-head')
    <div id="for-alert"></div>

    @if (Session::has('message'))
        <div class='alert alert-success alert-style'>
            <strong>Ou yeah,</strong> {{ Session::get('message') }}
        </div>
    @endif

    <div class="profile-edit-page-header" style="margin-bottom:10px;">
        <h2>Manajemen Data Berita</h2>
        <div class="breadcrumbs">
            <a href="{{ route('dashboard') }}">Home</a>
            <span>Manajemen Data Berita</span>
        </div>
    </div>
@endsection

@section('content')
    
    <div class="col-md-12">
        <div class="dashboard-list-box fl-wrap">
            <div class="dashboard-header fl-wrap">
                <div class="box-title">
                    <h3>Data Berita</h3>
                </div>
                <div style="float:right;width:100px;">
                    <a href="{{ route('berita-admin.create') }}" class="btn btn-success btn-sm">+ Tambah Data</a>
                </div>
            </div>
            <div class="col-md-12" style="text-align:left;">
                <br>
                <table id="user-table" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th style="width:15px;">#</th>
                            <th>Kategori</th>
                            <th>Judul</th>
                            <th>Isi</th>
                            <th>Status</th>
                            <th>Aksi</th>
                        </tr>
                       
                    </thead>
                    <tbody></tbody>
                </table>
                <br>
            </div>
        </div>
    </div>
@endsection

@section('modal')
    {{-- modal delete --}}
    <div class="main-register-wrap modal-delete">
        <div class="main-overlay"></div>
        <div class="main-register-holder">
            <div class="main-register fl-wrap">
                <div class="close-reg close-modal"><i class="fa fa-times"></i></div>
                <h3>Konfirmasi Penghapusan Data</h3>
                <p style="font-size:15px;">Apakah anda yakin akan menghapus data tersebut?</p>
                <a class="btn btn-danger close-modal" id="btn-delete">Ya, saya yakin.</a>
                <a class="btn btn-default close-modal">Tidak</a>
            </div>
        </div>
    </div>
@endsection

@section('foot-script')
    <script src="{{ asset('theme') }}/js/jquery.dataTables.min.js"></script>
    <script src="{{ asset('theme') }}/js/dataTables.bootstrap.min.js"></script>
    
    <script>
        $(function() {
            $('#user-table').DataTable();
            populateTable()
        });

        // show confirmation modal delete
        $('#user-table').on('click', '.modal-open-delete', function(e){
            e.preventDefault();
            $('.modal-delete').fadeIn();
            $("html, body").addClass("hid-body");

            var id = $(this).data('value')
            $('#btn-delete').data('value', id)
        })

        // delete data
        $("#btn-delete").on('click', function(){
            var id = $(this).data('value')
            
            $.ajax({
                url: "{{ url('api/berita-management') }}/" + id,
                type: "DELETE",
                dataType: 'json',
                success: function(res){
                    populateTable();
                    
                    $('#for-alert').html(
                        "<div class='alert alert-success alert-style'>" +
                            "<strong>Ou yeah,</strong> " + res.message +
                        "</div>"
                    )

                    closeAlert();
                }
            })
        })

        // populate table funciton
        function populateTable() {
            var no = 1;
            var url_edit='{{url("berita-admin")}}/';
            $.ajax({
                url: "{{ url('api/berita-management') }}" ,
                success: function(res) {
                    $('#user-table').dataTable({
                        "aaData": res.data,
                        "bDestroy": true,
                        "columns": [
                            { "data" : "id" },
                            { "data" : "cat_berita.nama_kategori" },
                            { "data" : "title" },
                            { "data" : "desc" },
                            { "data" : "flag" }
                           
                        ],
                        "columnDefs": [ {
                            "targets"   : 0,
                            "render"    : function () {
                                return no++;
                            }
                        },{
                            "targets"   : 5,
                            "data"      : "id",
                            "render"    : function (item) {
                                return  "<a class='btn btn-xs btn-warning' href='"+ url_edit+item +"/edit'>" +
                                            "<span class='fa fa-edit'></span>" +
                                        "</a> " +
                                        "<a class='btn btn-xs btn-danger modal-open-delete' data-value='"+ item +"'>" +
                                            "<span class='fa fa-trash'></span>" +
                                        "</a>"
                            }
                        } ]
                    })
                }   
            })
        }
    </script>
@endsection