routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/jumlah-ruas-jalan', 'ApiForDashboardController@jumlah_ruas_jalan');
Route::get('/data-kondisi-jalan', 'ApiForDashboardController@data_kondisi_jalan');
Route::get('/total-konstruksi-jalan', 'ApiForDashboardController@total_konstruksi_jalan');
Route::get('/data-jalan-all', 'ApiForDashboardController@all_data_jalan');

Route::get('/data-irigasi-by-kecamatan', 'ApiForDashboardController@data_irigasi_by_kecamatan');
Route::get('/all-data-irigasi', 'ApiForDashboardController@all_data_irigasi');
Route::get('/data-irigasi-total', 'ApiForDashboardController@data_irigasi_total');

Route::get('/data-jembatan-per-kecamatan', 'ApiForDashboardController@data_jembatan_per_kecamatan');
Route::get('/data-jembatan-all', 'ApiForDashboardController@data_jembatan_all');
Route::get('/data-jembatan-count', 'ApiForDashboardController@data_jembatan_count');

Route::get('/data-situ-count', 'ApiForDashboardController@data_situ_count');
Route::get('/data-situ-all', 'ApiForDashboardController@data_situ_all');
Route::get('/data-situ-per-kecamatan', 'ApiForDashboardController@data_situ_per_kecamatan');

Route::get('/data-sungai-count', 'ApiForDashboardController@data_sungai_count');
Route::get('/data-sungai-all', 'ApiForDashboardController@data_sungai_all');
Route::get('/data-sungai-per-kali', 'ApiForDashboardController@data_sungai_per_kali');
Route::get('/data-sungai-per-kecamatan', 'ApiForDashboardController@data_sungai_per_kecamatan');
Route::get('/data-sungai-per-jenis', 'ApiForDashboardController@data_sungai_per_jenis');

Route::get('welcome', 'HomeController@welcome')->name('utama');
Route::get('/', 'Frontend\DashboardController@index')->name('utama');

Route::get('hasil-usulan', 'UsulanVerifikasiController@usulan')->name('hasil.usulan');
Route::get('datairigasi', 'DataSituController@datairigasi')->name('hasil.usulan');

Route::get('hasil-verifikasi', 'UsulanVerifikasiController@verifikasi')->name('hasil.verifikasi');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/readcsv', 'RumahkumuhController@readcsv')->name('home');

Route::get('dashboard', 'Backend\DashboardController')->name('dashboard')->middleware('auth');

Route::get('user-management', 'Backend\UserManagementController')->name('user.management')->middleware('auth');

Route::resource('usulan', 'Backend\UsulanController')->middleware('auth');

Route::get('usulan/{id}/delete', 'Backend\UsulanController@delete')->middleware('auth');

Route::get('data-kumuh/{kecamatan}','RumahkumuhController@datakumuh')->name('datakumuh.kecamatan');
Route::get('data-jalan/{kecamatan}','DataJalanController@jumlahruasjalan')->name('datajalan.kecamatan');
Route::get('detail-data/{kecamatan}','DataJalanController@datajalan')->name('detail.jalan');
Route::get('detail-ruas-jalan/{ruas}','DataJalanController@dataruasjalan')->name('detail.ruas');
Route::get('load_data', 'DataJalanController@load_data')->name('load.data');
Route::get('load-map/{id}', 'DataJalanController@load_maps')->name('load.map');
Route::get('json_kml_jalan', 'DataJalanController@json_kml_jalan')->name('load.json_kml_jalan');
Route::post('upload_kml', 'DataJalanController@upload_kml')->name('upload_kml');

Route::get('detail-data-irigasi/{kecamatan}','DataIrigasiController@datairigasi')->name('detail.irigasi');
Route::get('detail-data-situ/{kecamatan}','DataSituController@datasitu')->name('detail.situ');
Route::get('detail-data-jembatan/{kecamatan}','DataJembatanController@datajembatan')->name('detail.jembatan');
Route::get('detail-data-sungai/{kecamatan}','DataSungaiController@datasungai')->name('detail.sungai');
Route::get('cek-jembatan','DataJembatanController@cek');

Route::resource('verifikasi', 'Backend\VerifiedController')->middleware('auth');

Route::get('verifikasi/{id}/delete', 'Backend\VerifiedController@delete')->middleware('auth');

Route::get('data-kumuh-json','RumahkumuhController@datakumuhjson')->name('datakumuhjson.kecamatan');

Route::get('detail-data-kumuh/{kecamatan}','RumahkumuhController@detail')->name('detail.kecamatan');

Route::get('detail-data-kumuh-kelurahan/{kecamatan}/{kelurahan}','RumahkumuhController@detailkelurahan')->name('detail.kelurahan');

Route::get('kategori-admin','TrxBeritaKategoriController@index')->middleware('auth');

Route::resource('berita-admin','TrxBeritaController',[ 'only' => ['index', 'create', 'store','edit'] ])->middleware('auth');

Route::resource('berita','Frontend\BeritaController',[ 'only' => ['index', 'show'] ]);

Route::get('show/{slug}','Frontend\BeritaController@detail');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     //\UniSharp\LaravelFilemanager\Lfm::routes();
 });

Route::resource('all-data-jalan', 'BackendDataJalanController')->middleware('auth');
Route::get('all-data-jalan/delete/{id}', 'BackendDataJalanController@destroy')->middleware('auth');
Route::get('data-jalan-kondisi/{id}', 'BackendDataJalanController@kondisi');

Route::resource('all-irigasi', 'BackendIrigasiController')->middleware('auth');
Route::get('all-irigasi/delete/{id}', 'BackendIrigasiController@destroy')->middleware('auth');

Route::resource('all-situ', 'BackendSituController')->middleware('auth');
Route::get('all-situ/delete/{id}', 'BackendSituController@destroy')->middleware('auth');

Route::resource('all-sungai', 'BackendSungaiController')->middleware('auth');
Route::get('all-sungai/delete/{id}', 'BackendSungaiController@destroy')->middleware('auth');

Route::resource('all-jembatan', 'BackendJembatanController')->middleware('auth');
Route::get('all-jembatan/delete/{id}', 'BackendJembatanController@destroy')->middleware('auth');

Route::get('download-file/{jenis}','Backend\DashboardController@download_file')->middleware('auth');

Route::get('view-tabular-jalan', 'DataJalanController@view_tabular_jalan')->name('view_tabular_jalan');
Route::get('view-tabular-irigasi', 'DataIrigasiController@view_tabular_irigasi')->name('view_tabular_irigasi');
Route::get('view-tabular-situ', 'DataSituController@view_tabular_situ')->name('view_tabular_situ');
Route::get('view-tabular-sungai', 'DataSungaiController@view_tabular_sungai')->name('view_tabular_sungai');
Route::get('view-tabular-jembatan', 'DataJembatanController@view_tabular_jembatan')->name('view_tabular_jembatan');

resources/views/backend/pages/situ/create.blade.php
@extends('backend.layouts.master')

@section('title')
    <title>Sistem Informasi Data Jalan - Admin Dashboard</title>
    <link rel="stylesheet" href="{{ asset('theme') }}/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ asset('theme') }}/css/dataTables.bootstrap.min.css">
    <style>
        td {
            font-size:12px;
        }
    </style>
@endsection

@section('content-head')
    <div id="for-alert"></div>

    @if (Session::has('message'))
        <div class='alert alert-success alert-style'>
            <strong>Ou yeah,</strong> {{ Session::get('message') }}
        </div>
    @endif

    @if ($errors->any())
        <div class='alert alert-danger alert-style'>
            <strong>Oops,</strong> Terjadi Kesalahan: <br>
            @foreach ($errors->all() as $item)
                <li>{{ $item }}</li>
            @endforeach
        </div>
    @endif
    

    <div class="profile-edit-page-header" style="margin-bottom:10px;">
        <h2>Manajemen Data Situ</h2>
        <div class="breadcrumbs">
            <a href="{{ route('dashboard') }}">Home</a>
            <span>Manajemen Data Situ</span>
        </div>
    </div>
@endsection

@section('content')
    
    <div class="col-md-12">
        <div class="dashboard-list-box fl-wrap">
            <div class="dashboard-header fl-wrap">
                <div class="box-title">
                    <h3>Formulir Input Data Situ</h3>
                </div>
            </div>
            <div class="col-md-12" style="text-align:left;">
                <br>
                    <div class="profile-edit-container">
                        <form action="{{ route('all-situ.store') }}" method="post" enctype="multipart/form-data">
                            @csrf

                            <div class="custom-form">

                                <label>Kecamatan<i class="fa fa-arrow-right"></i>  </label>
                                <select name="id_kecamatan" class="chosen-select">
                                    <option value="">-- Pilih --</option>
                                    @foreach ($kecamatan as $item)
                                        <option value="{{ $item->id }}">{{ $item->nama_kecamatan }}</option>
                                    @endforeach
                                </select>

                                <label>Nama Situ<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="nama_situ">

                                <label>DAS<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="das">

                                <label>Luas Asal<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="luas_asal">

                                <label>Luas Sekarang<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="luas_sekarang">

                                <label>Pengelolaan Pusat<i class="fa fa-arrow-right"></i>  </label>
                                <select name="pengelolaan_pusat" class="chosen-select">
                                    <option value="">-- Pilih --</option>
                                    <option value="1">Ya</option>
                                    <option value="0">Tidak</option>
                                </select>

                                <label>Pengelolaan Provinsi<i class="fa fa-arrow-right"></i>  </label>
                                <select name="pengelolaan_provinsi" class="chosen-select">
                                    <option value="">-- Pilih --</option>
                                    <option value="1">Ya</option>
                                    <option value="0">Tidak</option>
                                </select>

                                <label>Pengelolaan Kabupaten<i class="fa fa-arrow-right"></i>  </label>
                                <select name="pengelolaan_kabupaten" class="chosen-select">
                                    <option value="">-- Pilih --</option>
                                    <option value="1">Ya</option>
                                    <option value="0">Tidak</option>
                                </select>

                                <label>Kondisi<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="kondisi">

                                <label>Keterangan<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="keterangan">

                                <legend>
                                    Foto Situ <i>(opsional)</i>
                                </legend>

                                <label>Foto Situ 1</i>  </label>
                                <input type="file" name="foto_1" class="form-control">

                                <label>Foto Situ 2</i>  </label>
                                <input type="file" name="foto_2" class="form-control">

                                <label>Foto Situ 3</label>
                                <input type="file" name="foto_3" class="form-control">

                                <input type="submit" class="btn big-btn color-bg flat-btn" style="margin:20px 0;" value="Simpan Data">
                            </div>
                        </form>
                    </div>
                <br>
            </div>
        </div>
    </div>
@endsection

@section('modal')
    {{-- modal delete --}}
    <div class="main-register-wrap modal-delete">
        <div class="main-overlay"></div>
        <div class="main-register-holder">
            <div class="main-register fl-wrap">
                <div class="close-reg close-modal"><i class="fa fa-times"></i></div>
                <h3>Konfirmasi Penghapusan Data</h3>
                <p style="font-size:15px;">Apakah anda yakin akan menghapus data tersebut?</p>
                <a class="btn btn-danger close-modal" id="btn-delete">Ya, saya yakin.</a>
                <a class="btn btn-default close-modal">Tidak</a>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pages/situ/edit.blade.php
@extends('backend.layouts.master')

@section('title')
    <title>Sistem Informasi Data Jalan - Admin Dashboard</title>
    <link rel="stylesheet" href="{{ asset('theme') }}/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ asset('theme') }}/css/dataTables.bootstrap.min.css">
    <style>
        td {
            font-size:12px;
        }
    </style>
@endsection

@section('content-head')
    <div id="for-alert"></div>

    @if (Session::has('message'))
        <div class='alert alert-success alert-style'>
            <strong>Ou yeah,</strong> {{ Session::get('message') }}
        </div>
    @endif

    @if ($errors->any())
        <div class='alert alert-danger alert-style'>
            <strong>Oops,</strong> Terjadi Kesalahan: <br>
            @foreach ($errors->all() as $item)
                <li>{{ $item }}</li>
            @endforeach
        </div>
    @endif
    

    <div class="profile-edit-page-header" style="margin-bottom:10px;">
        <h2>Manajemen Data Situ</h2>
        <div class="breadcrumbs">
            <a href="{{ route('dashboard') }}">Home</a>
            <span>Manajemen Data Situ</span>
        </div>
    </div>
@endsection

@section('content')
    
    <div class="col-md-12">
        <div class="dashboard-list-box fl-wrap">
            <div class="dashboard-header fl-wrap">
                <div class="box-title">
                    <h3>Formulir Edit Data Situ</h3>
                </div>
            </div>
            <div class="col-md-12" style="text-align:left;">
                <br>
                    <div class="profile-edit-container">
                        <form action="{{ route('all-situ.update', $data->id) }}" method="post">
                            @csrf
                            @method('PUT')

                            <div class="custom-form">

                                <label>Kecamatan<i class="fa fa-arrow-right"></i>  </label>
                                <select name="id_kecamatan" class="chosen-select">
                                    <option value="">-- Pilih --</option>
                                    @foreach ($kecamatan as $item)
                                        @if ($data->id_kecamatan==$item->id)
                                            <option value="{{ $item->id }}" selected>{{ $item->nama_kecamatan }}</option>
                                        @else
                                            <option value="{{ $item->id }}">{{ $item->nama_kecamatan }}</option>
                                        @endif
                                    @endforeach
                                </select>

                                <label>Nama Situ<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="nama_situ" value="{{ $data->nama_situ }}">

                                <label>DAS<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="das" value="{{ $data->das }}">

                                <label>Luas Asal<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="luas_asal" value="{{ $data->luas_asal }}">

                                <label>Luas Sekarang<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="luas_sekarang" value="{{ $data->luas_sekarang }}">

                                <label>Pengelolaan Pusat<i class="fa fa-arrow-right"></i>  </label>
                                <select name="pengelolaan_pusat" class="chosen-select">
                                    <option value="">-- Pilih --</option>
                                    <option value="1" {{ $data->pengelolaan_pusat==1 ? 'selected' : '' }}>Ya</option>
                                    <option value="0" {{ $data->pengelolaan_pusat==0 ? 'selected' : '' }}>Tidak</option>
                                </select>

                                <label>Pengelolaan Provinsi<i class="fa fa-arrow-right"></i>  </label>
                                <select name="pengelolaan_provinsi" class="chosen-select">
                                    <option value="">-- Pilih --</option>
                                    <option value="1" {{ $data->pengelolaan_provinsi==1 ? 'selected' : '' }}>Ya</option>
                                    <option value="0" {{ $data->pengelolaan_provinsi==0 ? 'selected' : '' }}>Tidak</option>
                                </select>

                                <label>Pengelolaan Kabupaten<i class="fa fa-arrow-right"></i>  </label>
                                <select name="pengelolaan_kabupaten" class="chosen-select">
                                    <option value="">-- Pilih --</option>
                                    <option value="1" {{ $data->pengelolaan_kabupaten==1 ? 'selected' : '' }}>Ya</option>
                                    <option value="0" {{ $data->pengelolaan_kabupaten==0 ? 'selected' : '' }}>Tidak</option>
                                </select>

                                <label>Kondisi<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="kondisi" value="{{ $data->kondisi }}">

                                <label>Keterangan<i class="fa fa-arrow-right"></i>  </label>
                                <input type="text" name="keterangan" value="{{ $data->keterangan }}">

                                <legend>
                                    Foto Situ <i>(kosongkan jika tidak ingin diganti)</i>
                                </legend>

                                <label>Foto Situ 1</i>  </label>
                                <img src="{{ asset('foto/situ/') }}/{{ $data->foto_1 }}" alt="Foto tidak ditemukan." style="height:150px;margin-bottom:10px;">
                                <input type="file" name="foto_1" class="form-control">

                                <label>Foto Situ 2</i>  </label>
                                <img src="{{ asset('foto/situ/') }}/{{ $data->foto_2 }}" alt="Foto tidak ditemukan." style="height:150px;margin-bottom:10px;">
                                <input type="file" name="foto_2" class="form-control">

                                <label>Foto Situ 3</label>
                                <img src="{{ asset('foto/situ/') }}/{{ $data->foto_3 }}" alt="Foto tidak ditemukan." style="height:150px;margin-bottom:10px;">
                                <input type="file" name="foto_3" class="form-control">

                                <input type="submit" class="btn big-btn color-bg flat-btn" style="margin:20px 0;" value="Simpan Data">
                            </div>
                        </form>
                    </div>
                <br>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pages/situ/excel.blade.php
<?php
    header("Content-Disposition: attachment; filename=Data-Situ.xls");
    header("Pragma: no-cache");
    header("Expires: 0");
    // $file = "Data-Jalan.xlsx" ;
    // header('Content-Disposition: attachment; filename='.$file);
    // header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    // header('Content-Length: ' . filesize($file));
    // header('Content-Transfer-Encoding: binary');
    // header('Cache-Control: must-revalidate');
    // header('Pragma: public');
    // ob_clean();
    // flush(); 
    // readfile($file);

?>
    
    <table border="1">
                    <thead border="1">
                        <tr>
                            <th rowspan="2" style="width:15px;">#</th>
                            <th rowspan="2">Nama SITU</th>
                            <th rowspan="2">Kecamatan</th>
                            <th rowspan="2">Desa</th>
                            <th rowspan="2">DAS</th>
                            <th colspan="2">Luas</th>
                            <th colspan="3">Pengelolaan</th>
                            <th rowspan="2">Kondisi</th>
                            <th rowspan="2">Keterangan</th>
                        </tr>
                        <tr>
                            <td>Asal (Ha)</td>
                            <td>Sekarang (Ha)</td>
                            <td>Pusat</td>
                            <td>Provinsi</td>
                            <td>Kabupaten</td>
                            
                        </tr>
                        
                    </thead>
                    <tbody>
                        @foreach ($data as $key => $item)
                            <tr>
                                <td>{{ $key = $key + 1 }}</td>
                                <td>{{ $item['nama_situ'] }}</td>
                                <td>{{ $item['kecamatan']['nama_kecamatan'] }}</td>
                                <td>{{ $item['kelurahan']['nama_kelurahan'] }}</td>
                                <td>{{ $item['das'] }}</td>
                                <td style="text-align:center">{{ number_format($item['luas_asal'],2,',','.') }}</td>
                                <td style="text-align:center">{{ number_format($item['luas_sekarang'],2,',','.') }}</td>
                                <td class="text-center">{{ $item['pengelolaan_pusat']==1 ? 'Pusat' : '' }}</td>
                                <td class="text-center">{{ $item['pengelolaan_provinsi']==1 ? 'Provinsi' : '' }}</td>
                                <td class="text-center">{{ $item['pengelolaan_kabupaten']==1 ? 'Kabupaten' : '' }}</td>
                                <td class="text-center">{{ $item['kondisi'] }}</td>
                                <td class="text-center">{{ $item['keterangan'] }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

resources/views/backend/pages/situ/index.blade.php
@extends('backend.layouts.master')

@section('title')
    <title>Sistem Informasi Data Jalan - Admin Dashboard</title>
    <link rel="stylesheet" href="{{ asset('theme') }}/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ asset('theme') }}/css/dataTables.bootstrap.min.css">
    <style>
        td {
            font-size:12px;
        }
    </style>
@endsection

@section('content-head')
    <div id="for-alert"></div>

    @if (Session::has('message'))
        <div class='alert alert-success alert-style'>
            <strong>Ou yeah,</strong> {{ Session::get('message') }}
        </div>
    @endif

    <div class="profile-edit-page-header" style="margin-bottom:10px;">
        <h2>Manajemen Data Situ</h2>
        <div class="breadcrumbs">
            <a href="{{ route('dashboard') }}">Home</a>
            <span>Manajemen Data Situ</span>
        </div>
    </div>
@endsection

@section('content')
    
    <div class="col-md-12">
        <div class="dashboard-list-box fl-wrap">
            <div class="dashboard-header fl-wrap">
                <div class="box-title">
                    <h3>Data Situ</h3>
                </div>
                <div style="float:right;width:100px;">
                    <a href="{{ route('all-situ.create') }}" class="btn btn-info btn-sm">+ Tambah Data</a>
                </div>
                <div style="float:right;width:100px;margin-right:20px;">
                    <a href="{{ url('download-file/situ') }}" class="btn btn-success btn-sm"><i class="fa fa-file-excel-o"></i> Download XLS</a>
                </div>
            </div>
            <div class="col-md-12 table-responsive" style="text-align:left;">
                <br>
                <table id="user-table" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th rowspan="2" style="width:15px;">#</th>
                            <th rowspan="2">Kecamatan</th>
                            <th rowspan="2">Nama Situ</th>
                            <th rowspan="2">DAS</th>
                            <th colspan="2">Luas</th>
                            <th colspan="3">Pengelolaan</th>
                            <th rowspan="2">Kondisi</th>
                            <th rowspan="2">Aksi</th>
                        </tr>
                        <tr>
                            <th>Asal</th>
                            <th>Sekarang</th>
                            <th>Pusat</th>
                            <th>Provinsi</th>
                            <th>Kabupaten</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($data as $key => $item)
                            <tr>
                                <td>{{ $key = $key + 1 }}</td>
                                <td>{{ $item->kecamatan->nama_kecamatan }}</td>
                                <td>{{ $item->nama_situ }}</td>
                                <td>{{ $item->das }}</td>
                                <td>{{ !is_null($item->luas_asal) ? $item->luas_asal." Ha" : '-' }}</td>
                                <td>{{ !is_null($item->luas_sekarang) ? $item->luas_sekarang." Ha" : '-' }}</td>
                                <td>
                                    @if ($item->pengelolaan_pusat==0)
                                        -
                                    @else
                                        <i class="fa fa-check"></i>
                                    @endif
                                </td>
                                <td>
                                    @if ($item->pengelolaan_provinsi==0)
                                        -
                                    @else
                                        <i class="fa fa-check"></i>
                                    @endif
                                </td>
                                <td>
                                    @if ($item->pengelolaan_kabupaten==0)
                                        -
                                    @else
                                        <i class="fa fa-check"></i>
                                    @endif
                                </td>
                                <td>{{ $item->kondisi }}</td>
                                <td>
                                    <a href="{{ route('all-situ.edit', $item->id) }}" class="btn btn-xs btn-warning"><i class="fa fa-edit"></i></a>
                                    <a data-value="{{ $item->id }}" href="" class="btn btn-xs btn-danger modal-open-delete"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                <br>
            </div>
        </div>
    </div>
@endsection

@section('modal')
    {{-- modal delete --}}
    <div class="main-register-wrap modal-delete">
        <div class="main-overlay"></div>
        <div class="main-register-holder">
            <div class="main-register fl-wrap">
                <div class="close-reg close-modal"><i class="fa fa-times"></i></div>
                <h3>Konfirmasi Penghapusan Data</h3>
                <p style="font-size:15px;">Apakah anda yakin akan menghapus data tersebut?</p>
                <a class="btn btn-danger close-modal" id="btn-delete">Ya, saya yakin.</a>
                <a class="btn btn-default close-modal">Tidak</a>
            </div>
        </div>
    </div>
@endsection

@section('foot-script')
    <script src="{{ asset('theme') }}/js/jquery.dataTables.min.js"></script>
    <script src="{{ asset('theme') }}/js/dataTables.bootstrap.min.js"></script>
    
    <script>
        $('#user-table').DataTable()
        
        // show confirmation modal delete
        $('#user-table').on('click', '.modal-open-delete', function(e){
            e.preventDefault();
            $('.modal-delete').fadeIn();
            $("html, body").addClass("hid-body");

            var id = $(this).data('value')
            $('#btn-delete').attr('href', "{{ url('all-situ/delete') }}/" + id)
        })

        // delete data
        $("#btn-delete").on('click', function(){
            populateTable();
            
            $('#for-alert').html(
                "<div class='alert alert-success alert-style'>" +
                    "<strong>Ou yeah,</strong> " + res.message +
                "</div>"
            )

            closeAlert();
        })
    </script>
<style>
.btn i {
    padding-left: unset !important;
}
.pagination>li>a, .pagination>li>span
{
    padding:12px !important;
}
li.previous, li.next
{
    text-align:center !important;
}
.font100
{
    font-weight: 400;
    font-size: 100% !important;
}
.bottom-10
{
    padding-bottom:10px;
}
#kondisi-table th{
    background-color: #4DB7FE !important;
    color:white;
    font-weight: 550;
}
#kondisi-table td{
    font-weight: 600;
}
.label-lightblue
{
    background:lightblue;
}
</style>
@endsection